# Uncomment this line to define a global platform for your project
platform :tvos, '9.2'

# Uncomment this line if you're using Swift
use_frameworks!

target 'Movie4K' do
  # Specify Swift version for all pods
  swift_version = '5.0'

  # Add pods here
  pod 'SwiftyJSON', '2.3.2'
  pod 'Alamofire', '3.4.0'
  pod 'HTMLReader', '0.9.6'
  pod 'Cosmos', '1.2.2'
  pod 'MarqueeLabel/Swift', '2.7.4'
  pod 'SVProgressHUD', :git => 'https://github.com/SVProgressHUD/SVProgressHUD.git'
  pod 'PromiseKit', '3.2.0'

  # Set the Swift version
  post_install do |installer|
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['SWIFT_VERSION'] = swift_version
      end
    end
  end
end
